<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Samuel Cárdenas García">
<meta name="dcterms.date" content="2026-09-25">

<title>Tarea 1 — Caja de herramientas de pronóstico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="informe_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="informe_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="informe_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="informe_files/libs/quarto-html/popper.min.js"></script>
<script src="informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="informe_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="informe_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#protocolo-de-análisis" id="toc-protocolo-de-análisis" class="nav-link" data-scroll-target="#protocolo-de-análisis"><span class="header-section-number">2</span> Protocolo de análisis</a></li>
  <li><a href="#resumen-de-los-ocho-ejemplos" id="toc-resumen-de-los-ocho-ejemplos" class="nav-link" data-scroll-target="#resumen-de-los-ocho-ejemplos"><span class="header-section-number">3</span> Resumen de los ocho ejemplos</a></li>
  <li><a href="#descripción-de-las-pruebas" id="toc-descripción-de-las-pruebas" class="nav-link" data-scroll-target="#descripción-de-las-pruebas"><span class="header-section-number">4</span> Descripción de las pruebas</a>
  <ul class="collapse">
  <li><a href="#ljungbox-sobre-la-serie" id="toc-ljungbox-sobre-la-serie" class="nav-link" data-scroll-target="#ljungbox-sobre-la-serie"><span class="header-section-number">4.1</span> Ljung–Box sobre la serie</a></li>
  <li><a href="#contrastes-individuales-de-autocorrelación" id="toc-contrastes-individuales-de-autocorrelación" class="nav-link" data-scroll-target="#contrastes-individuales-de-autocorrelación"><span class="header-section-number">4.2</span> Contrastes individuales de autocorrelación</a></li>
  <li><a href="#media-cero-de-los-errores" id="toc-media-cero-de-los-errores" class="nav-link" data-scroll-target="#media-cero-de-los-errores"><span class="header-section-number">4.3</span> Media cero de los errores</a></li>
  <li><a href="#ljungbox-de-los-errores" id="toc-ljungbox-de-los-errores" class="nav-link" data-scroll-target="#ljungbox-de-los-errores"><span class="header-section-number">4.4</span> Ljung–Box de los errores</a></li>
  <li><a href="#jarquebera" id="toc-jarquebera" class="nav-link" data-scroll-target="#jarquebera"><span class="header-section-number">4.5</span> Jarque–Bera</a></li>
  <li><a href="#durbinwatson" id="toc-durbinwatson" class="nav-link" data-scroll-target="#durbinwatson"><span class="header-section-number">4.6</span> Durbin–Watson</a></li>
  </ul></li>
  <li><a href="#análisis-individual" id="toc-análisis-individual" class="nav-link" data-scroll-target="#análisis-individual"><span class="header-section-number">5</span> Análisis individual</a>
  <ul class="collapse">
  <li><a href="#nile-media" id="toc-nile-media" class="nav-link" data-scroll-target="#nile-media"><span class="header-section-number">5.1</span> 1. Nile — media</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie" id="toc-ljungbox-de-la-serie" class="nav-link" data-scroll-target="#ljungbox-de-la-serie"><span class="header-section-number">5.1.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales" id="toc-autocorrelaciones-individuales" class="nav-link" data-scroll-target="#autocorrelaciones-individuales"><span class="header-section-number">5.1.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización" id="toc-ajuste-parámetros-y-optimización" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización"><span class="header-section-number">5.1.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error" id="toc-medidas-de-error" class="nav-link" data-scroll-target="#medidas-de-error"><span class="header-section-number">5.1.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores" id="toc-validación-de-errores" class="nav-link" data-scroll-target="#validación-de-errores"><span class="header-section-number">5.1.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre" id="toc-comparación-con-el-referente-y-cierre" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre"><span class="header-section-number">5.1.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#nottem-mm" id="toc-nottem-mm" class="nav-link" data-scroll-target="#nottem-mm"><span class="header-section-number">5.2</span> 2. nottem — mm</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-1" id="toc-ljungbox-de-la-serie-1" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-1"><span class="header-section-number">5.2.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-1" id="toc-autocorrelaciones-individuales-1" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-1"><span class="header-section-number">5.2.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-1" id="toc-ajuste-parámetros-y-optimización-1" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-1"><span class="header-section-number">5.2.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-1" id="toc-medidas-de-error-1" class="nav-link" data-scroll-target="#medidas-de-error-1"><span class="header-section-number">5.2.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-1" id="toc-validación-de-errores-1" class="nav-link" data-scroll-target="#validación-de-errores-1"><span class="header-section-number">5.2.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-1" id="toc-comparación-con-el-referente-y-cierre-1" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-1"><span class="header-section-number">5.2.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#lakehuron-ses" id="toc-lakehuron-ses" class="nav-link" data-scroll-target="#lakehuron-ses"><span class="header-section-number">5.3</span> 3. LakeHuron — ses</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-2" id="toc-ljungbox-de-la-serie-2" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-2"><span class="header-section-number">5.3.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-2" id="toc-autocorrelaciones-individuales-2" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-2"><span class="header-section-number">5.3.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-2" id="toc-ajuste-parámetros-y-optimización-2" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-2"><span class="header-section-number">5.3.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-2" id="toc-medidas-de-error-2" class="nav-link" data-scroll-target="#medidas-de-error-2"><span class="header-section-number">5.3.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-2" id="toc-validación-de-errores-2" class="nav-link" data-scroll-target="#validación-de-errores-2"><span class="header-section-number">5.3.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-2" id="toc-comparación-con-el-referente-y-cierre-2" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-2"><span class="header-section-number">5.3.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#wwwusage-dmm" id="toc-wwwusage-dmm" class="nav-link" data-scroll-target="#wwwusage-dmm"><span class="header-section-number">5.4</span> 4. WWWusage — dmm</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-3" id="toc-ljungbox-de-la-serie-3" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-3"><span class="header-section-number">5.4.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-3" id="toc-autocorrelaciones-individuales-3" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-3"><span class="header-section-number">5.4.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-3" id="toc-ajuste-parámetros-y-optimización-3" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-3"><span class="header-section-number">5.4.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-3" id="toc-medidas-de-error-3" class="nav-link" data-scroll-target="#medidas-de-error-3"><span class="header-section-number">5.4.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-3" id="toc-validación-de-errores-3" class="nav-link" data-scroll-target="#validación-de-errores-3"><span class="header-section-number">5.4.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-3" id="toc-comparación-con-el-referente-y-cierre-3" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-3"><span class="header-section-number">5.4.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#airmiles-lineal" id="toc-airmiles-lineal" class="nav-link" data-scroll-target="#airmiles-lineal"><span class="header-section-number">5.5</span> 5. airmiles — lineal</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-4" id="toc-ljungbox-de-la-serie-4" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-4"><span class="header-section-number">5.5.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-4" id="toc-autocorrelaciones-individuales-4" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-4"><span class="header-section-number">5.5.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-4" id="toc-ajuste-parámetros-y-optimización-4" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-4"><span class="header-section-number">5.5.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-4" id="toc-medidas-de-error-4" class="nav-link" data-scroll-target="#medidas-de-error-4"><span class="header-section-number">5.5.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-4" id="toc-validación-de-errores-4" class="nav-link" data-scroll-target="#validación-de-errores-4"><span class="header-section-number">5.5.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-4" id="toc-comparación-con-el-referente-y-cierre-4" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-4"><span class="header-section-number">5.5.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#ukdriverdeaths-cuadratica" id="toc-ukdriverdeaths-cuadratica" class="nav-link" data-scroll-target="#ukdriverdeaths-cuadratica"><span class="header-section-number">5.6</span> 6. UKDriverDeaths — cuadratica</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-5" id="toc-ljungbox-de-la-serie-5" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-5"><span class="header-section-number">5.6.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-5" id="toc-autocorrelaciones-individuales-5" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-5"><span class="header-section-number">5.6.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-5" id="toc-ajuste-parámetros-y-optimización-5" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-5"><span class="header-section-number">5.6.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-5" id="toc-medidas-de-error-5" class="nav-link" data-scroll-target="#medidas-de-error-5"><span class="header-section-number">5.6.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-5" id="toc-validación-de-errores-5" class="nav-link" data-scroll-target="#validación-de-errores-5"><span class="header-section-number">5.6.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-5" id="toc-comparación-con-el-referente-y-cierre-5" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-5"><span class="header-section-number">5.6.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#johnsonjohnson-exponencial" id="toc-johnsonjohnson-exponencial" class="nav-link" data-scroll-target="#johnsonjohnson-exponencial"><span class="header-section-number">5.7</span> 7. JohnsonJohnson — exponencial</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-6" id="toc-ljungbox-de-la-serie-6" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-6"><span class="header-section-number">5.7.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-6" id="toc-autocorrelaciones-individuales-6" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-6"><span class="header-section-number">5.7.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-6" id="toc-ajuste-parámetros-y-optimización-6" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-6"><span class="header-section-number">5.7.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-6" id="toc-medidas-de-error-6" class="nav-link" data-scroll-target="#medidas-de-error-6"><span class="header-section-number">5.7.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-6" id="toc-validación-de-errores-6" class="nav-link" data-scroll-target="#validación-de-errores-6"><span class="header-section-number">5.7.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-6" id="toc-comparación-con-el-referente-y-cierre-6" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-6"><span class="header-section-number">5.7.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  <li><a href="#austres-holt" id="toc-austres-holt" class="nav-link" data-scroll-target="#austres-holt"><span class="header-section-number">5.8</span> 8. austres — holt</a>
  <ul class="collapse">
  <li><a href="#ljungbox-de-la-serie-7" id="toc-ljungbox-de-la-serie-7" class="nav-link" data-scroll-target="#ljungbox-de-la-serie-7"><span class="header-section-number">5.8.1</span> Ljung–Box de la serie</a></li>
  <li><a href="#autocorrelaciones-individuales-7" id="toc-autocorrelaciones-individuales-7" class="nav-link" data-scroll-target="#autocorrelaciones-individuales-7"><span class="header-section-number">5.8.2</span> Autocorrelaciones individuales</a></li>
  <li><a href="#ajuste-parámetros-y-optimización-7" id="toc-ajuste-parámetros-y-optimización-7" class="nav-link" data-scroll-target="#ajuste-parámetros-y-optimización-7"><span class="header-section-number">5.8.3</span> Ajuste, parámetros y optimización</a></li>
  <li><a href="#medidas-de-error-7" id="toc-medidas-de-error-7" class="nav-link" data-scroll-target="#medidas-de-error-7"><span class="header-section-number">5.8.4</span> Medidas de error</a></li>
  <li><a href="#validación-de-errores-7" id="toc-validación-de-errores-7" class="nav-link" data-scroll-target="#validación-de-errores-7"><span class="header-section-number">5.8.5</span> Validación de errores</a></li>
  <li><a href="#comparación-con-el-referente-y-cierre-7" id="toc-comparación-con-el-referente-y-cierre-7" class="nav-link" data-scroll-target="#comparación-con-el-referente-y-cierre-7"><span class="header-section-number">5.8.6</span> Comparación con el referente y cierre</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#contraejemplo" id="toc-contraejemplo" class="nav-link" data-scroll-target="#contraejemplo"><span class="header-section-number">6</span> Contraejemplo</a></li>
  <li><a href="#verificaciones-de-implementación" id="toc-verificaciones-de-implementación" class="nav-link" data-scroll-target="#verificaciones-de-implementación"><span class="header-section-number">7</span> Verificaciones de implementación</a></li>
  <li><a href="#conclusiones-generales" id="toc-conclusiones-generales" class="nav-link" data-scroll-target="#conclusiones-generales"><span class="header-section-number">8</span> Conclusiones generales</a></li>
  <li><a href="#reproducibilidad" id="toc-reproducibilidad" class="nav-link" data-scroll-target="#reproducibilidad"><span class="header-section-number">9</span> Reproducibilidad</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tarea 1 — Caja de herramientas de pronóstico</h1>
<p class="subtitle lead">Series de tiempo univariadas — código 3009297</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Samuel Cárdenas García </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Este informe documenta la ejecución de los ocho métodos de pronóstico implementados manualmente en R. El análisis sigue el protocolo de la tarea: descripción de cada serie, gráfico, correlograma, lectura de los patrones, separación entre estimación y validación, selección de parámetros mediante una rejilla cuando corresponde, medidas de error, validación de residuos y comparación con el pronóstico ingenuo.</p>
<p>Los cálculos se ejecutan a partir de los archivos del repositorio mediante rutas relativas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">width =</span> <span class="dv">100</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/00-lectura.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'patchwork' was built under R version 4.4.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/01-graficos.R"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/02-metodos.R"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/03-evaluacion.R"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejecuta los ocho ejemplos y guarda las figuras/resultados.</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"ejemplos/ejemplos.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: Nile 
Método: media 
Justificación: Serie anual sin estacionalidad explícita. La media histórica proporciona un pronóstico constante basado en toda la información disponible. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: nottem 
Método: mm 
Justificación: Serie mensual. Se utiliza una media móvil para evaluar el comportamiento de corto plazo mediante un parámetro k seleccionado por MSE. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: LakeHuron 
Método: ses 
Justificación: Serie anual. El suavizamiento exponencial simple permite actualizar el nivel con un peso alpha seleccionado mediante MSE. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: WWWusage 
Método: dmm 
Justificación: Serie con evolución temporal y tendencia local. La doble media móvil permite incorporar nivel y tendencia mediante k. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: airmiles 
Método: lineal 
Justificación: Serie anual con crecimiento temporal. Se utiliza una tendencia lineal estimada mediante las ecuaciones normales. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: UKDriverDeaths 
Método: cuadratica 
Justificación: Serie mensual. Se utiliza una tendencia cuadrática para representar una posible curvatura en la evolución temporal. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: JohnsonJohnson 
Método: exponencial 
Justificación: Serie trimestral con crecimiento aproximadamente multiplicativo. Se utiliza la transformación logarítmica para estimar una tendencia exponencial. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: austres 
Método: holt 
Justificación: Serie trimestral con nivel y tendencia. Holt actualiza ambos componentes mediante alpha y beta seleccionados por MSE. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================
Ejemplo: AirPassengers 
Método: media 
Justificación: Contraejemplo deliberado. La serie presenta estructura estacional y crecimiento, mientras que la media histórica no representa explícitamente esos componentes. 
====================================================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 17
  serie          metodo      parametro MSE_estimacion MAD_estimacion MAPE_estimacion MASE_estimacion
  &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt;              &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
1 Nile           media       ninguno        31112.           145.            17.9             1.09  
2 nottem         mm          parametr…         47.0            5.80          12.0             2.11  
3 LakeHuron      ses         parametr…          0.558          0.577          0.0996          1.00  
4 WWWusage       dmm         parametr…         22.7            3.83           3.07            0.861 
5 airmiles       lineal      lineal       5322546.          1971.           117.              1.69  
6 UKDriverDeaths cuadratica  cuadrati…      65187.           205.            12.1             1.31  
7 JohnsonJohnson exponencial exponenc…          0.322          0.364         11.9             0.693 
8 austres        holt        alpha=0.…        129.             7.53           0.0514          0.0359
# ℹ 10 more variables: MSE_validacion &lt;dbl&gt;, MAD_validacion &lt;dbl&gt;, MAPE_validacion &lt;dbl&gt;,
#   MASE_validacion &lt;dbl&gt;, MASE_ingenuo &lt;dbl&gt;, optimo_en_borde &lt;lgl&gt;, LB_p &lt;dbl&gt;, JB_p &lt;dbl&gt;,
#   DW &lt;dbl&gt;, LB_serie_p &lt;dbl&gt;

Optimización: un TRUE en optimo_en_borde indica que el mínimo de la rejilla está en uno de sus bordes; en el informe debe interpretarse antes de ampliar o cambiar la rejilla.
# A tibble: 1 × 17
  serie         metodo parametro MSE_estimacion MAD_estimacion MAPE_estimacion MASE_estimacion
  &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;              &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
1 AirPassengers media  ninguno           11494.           83.4            26.8            2.74
# ℹ 10 more variables: MSE_validacion &lt;dbl&gt;, MAD_validacion &lt;dbl&gt;, MAPE_validacion &lt;dbl&gt;,
#   MASE_validacion &lt;dbl&gt;, MASE_ingenuo &lt;dbl&gt;, optimo_en_borde &lt;lgl&gt;, LB_p &lt;dbl&gt;, JB_p &lt;dbl&gt;,
#   DW &lt;dbl&gt;, LB_serie_p &lt;dbl&gt;

Diferencia máxima ACF manual vs acf(): 4.440892e-16 

Verificación de tendencias contra lm(): OK
$manual
$manual$estadistico
[1] 130.18

$manual$gl
[1] 24

$manual$valor_critico_5
[1] 36.41503

$manual$p_valor
[1] 1.439183e-16

$manual$rechazar_5
[1] TRUE


$R

    Box-Ljung test

data:  x
X-squared = 130.18, df = 24, p-value &lt; 2.2e-16


$diferencia_Q
[1] 1.705303e-13

$diferencia_p
[1] 3.289604e-17

$coincide
[1] TRUE

$diferencia_maxima
[1] 0

$coincide
[1] TRUE

$diferencia_nivel
[1] 0

$diferencia_tendencia
[1] 0

$coincide
[1] TRUE


====================================================
Ejecución finalizada correctamente.
Número de ejemplos: 8 
Contraejemplo: AirPassengers 
Diferencia máxima ACF: 4.440892e-16 
====================================================</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Nota:</strong> la ejecución puede mostrar warnings de <code>ggplot2</code> relacionados con la escala de fechas y filas omitidas en algunos gráficos. Estos mensajes no detienen la ejecución; el script debe terminar con <code>Ejecución finalizada correctamente.</code></p>
</blockquote>
</section>
<section id="protocolo-de-análisis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Protocolo de análisis</h1>
<p>Para cada serie se usa un tramo de estimación y un tramo final de validación. La longitud de validación se calcula como</p>
<p><span class="math display">\[
h=\min\{12,\lfloor 0.2T\rfloor\},
\]</span></p>
<p>y, para series estacionales, se garantiza al menos un ciclo completo.</p>
<p>Las medidas de error usadas son</p>
<p><span class="math display">\[
MSE=\frac{1}{h}\sum e_t^2,\qquad
MAD=\frac{1}{h}\sum |e_t|,
\]</span></p>
<p><span class="math display">\[
MAPE=100\frac{1}{h}\sum\left|\frac{e_t}{y_t}\right|,
\qquad
MASE=\frac{MAD}{\text{escala ingenua}}.
\]</span></p>
<p>La escala del MASE se calcula únicamente sobre el tramo de estimación y corresponde al error absoluto medio del pronóstico ingenuo; en series estacionales se utiliza el ingenuo estacional.</p>
<p>La prueba de Ljung–Box usada en el código es</p>
<p><span class="math display">\[
Q_m=T(T+2)\sum_{h=1}^{m}\frac{r_h^2}{T-h},
\]</span></p>
<p>que bajo la hipótesis nula se contrasta con una distribución <span class="math inline">\(\chi^2_{m-p}\)</span> para los residuos de un método con <span class="math inline">\(p\)</span> parámetros estimados.</p>
<p>La prueba de Jarque–Bera es</p>
<p><span class="math display">\[
JB=\frac{N}{6}\left[A^2+\frac{(K-3)^2}{4}\right],
\]</span></p>
<p>con distribución asintótica <span class="math inline">\(\chi^2_2\)</span> bajo normalidad.</p>
<p>El estadístico de Durbin–Watson es</p>
<p><span class="math display">\[
d=\frac{\sum_{t=2}^{N}(e_t-e_{t-1})^2}
        {\sum_{t=1}^{N}e_t^2}.
\]</span></p>
</section>
<section id="resumen-de-los-ocho-ejemplos" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Resumen de los ocho ejemplos</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tabla_resultados</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 17
  serie          metodo      parametro MSE_estimacion MAD_estimacion MAPE_estimacion MASE_estimacion
  &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt;              &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
1 Nile           media       ninguno        31112.           145.            17.9             1.09  
2 nottem         mm          parametr…         47.0            5.80          12.0             2.11  
3 LakeHuron      ses         parametr…          0.558          0.577          0.0996          1.00  
4 WWWusage       dmm         parametr…         22.7            3.83           3.07            0.861 
5 airmiles       lineal      lineal       5322546.          1971.           117.              1.69  
6 UKDriverDeaths cuadratica  cuadrati…      65187.           205.            12.1             1.31  
7 JohnsonJohnson exponencial exponenc…          0.322          0.364         11.9             0.693 
8 austres        holt        alpha=0.…        129.             7.53           0.0514          0.0359
# ℹ 10 more variables: MSE_validacion &lt;dbl&gt;, MAD_validacion &lt;dbl&gt;, MAPE_validacion &lt;dbl&gt;,
#   MASE_validacion &lt;dbl&gt;, MASE_ingenuo &lt;dbl&gt;, optimo_en_borde &lt;lgl&gt;, LB_p &lt;dbl&gt;, JB_p &lt;dbl&gt;,
#   DW &lt;dbl&gt;, LB_serie_p &lt;dbl&gt;</code></pre>
</div>
</div>
<p>La tabla contiene el método, los parámetros seleccionados, las medidas de error en estimación y validación, el MASE del referente ingenuo y los principales diagnósticos de residuos.</p>
</section>
<section id="descripción-de-las-pruebas" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Descripción de las pruebas</h1>
<p>En cada prueba se reportan: (1) hipótesis nula y alterna, (2) estadístico, distribución y grados de libertad cuando corresponden, (3) región de rechazo al 5 %, (4) valor observado y valor p, (5) decisión y (6) lectura para la serie o el método.</p>
<section id="ljungbox-sobre-la-serie" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="ljungbox-sobre-la-serie"><span class="header-section-number">4.1</span> Ljung–Box sobre la serie</h2>
<p>Se plantea <span class="math inline">\(H_0:r_1=\cdots=r_m=0\)</span> frente a <span class="math inline">\(H_1:\)</span> al menos una autocorrelación es distinta de cero. El estadístico es <span class="math inline">\(Q_m\)</span> y bajo <span class="math inline">\(H_0\)</span> sigue aproximadamente <span class="math inline">\(\chi^2_m\)</span> porque aquí <span class="math inline">\(p=0\)</span>. Se rechaza al 5 % si <span class="math inline">\(Q_m&gt;\chi^2_{m,0.95}\)</span>, equivalentemente si <span class="math inline">\(p&lt;0.05\)</span>.</p>
</section>
<section id="contrastes-individuales-de-autocorrelación" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="contrastes-individuales-de-autocorrelación"><span class="header-section-number">4.2</span> Contrastes individuales de autocorrelación</h2>
<p>Para cada rezago <span class="math inline">\(h\)</span> se contrasta <span class="math inline">\(H_0:r_h=0\)</span> frente a <span class="math inline">\(H_1:r_h\neq0\)</span>. Bajo la aproximación normal se usa <span class="math inline">\(Z_h=r_h\sqrt{T}\sim N(0,1)\)</span>, con región de rechazo <span class="math inline">\(|Z_h|&gt;1.96\)</span>. El mismo criterio aparece gráficamente mediante la banda <span class="math inline">\(\pm1.96/\sqrt{T}\)</span>.</p>
</section>
<section id="media-cero-de-los-errores" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="media-cero-de-los-errores"><span class="header-section-number">4.3</span> Media cero de los errores</h2>
<p>Se contrasta <span class="math inline">\(H_0:\mu_e=0\)</span> frente a <span class="math inline">\(H_1:\mu_e\neq0\)</span>. El estadístico es <span class="math inline">\(t=\bar e/(s_e/\sqrt N)\)</span>, con distribución <span class="math inline">\(t_{N-1}\)</span>. Se rechaza al 5 % si <span class="math inline">\(|t|&gt;t_{N-1,0.975}\)</span>.</p>
</section>
<section id="ljungbox-de-los-errores" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="ljungbox-de-los-errores"><span class="header-section-number">4.4</span> Ljung–Box de los errores</h2>
<p>Se contrasta <span class="math inline">\(H_0:r_1=\cdots=r_m=0\)</span> frente a <span class="math inline">\(H_1:\)</span> alguna autocorrelación no es cero. El estadístico es <span class="math inline">\(Q_m\)</span> y se compara con <span class="math inline">\(\chi^2_{m-p}\)</span>, donde <span class="math inline">\(p\)</span> es el número de parámetros estimados por el método. Se rechaza si <span class="math inline">\(Q_m&gt;\chi^2_{m-p,0.95}\)</span>.</p>
</section>
<section id="jarquebera" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="jarquebera"><span class="header-section-number">4.5</span> Jarque–Bera</h2>
<p>Se contrasta <span class="math inline">\(H_0:\)</span> los errores tienen asimetría 0 y curtosis 3 frente a la alternativa de no normalidad. El estadístico <span class="math inline">\(JB\)</span> se compara con <span class="math inline">\(\chi^2_2\)</span>. Se rechaza si <span class="math inline">\(JB&gt;\chi^2_{2,0.95}\)</span>.</p>
</section>
<section id="durbinwatson" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="durbinwatson"><span class="header-section-number">4.6</span> Durbin–Watson</h2>
<p>Se usa <span class="math inline">\(d\)</span> para evaluar autocorrelación de primer orden. La referencia es <span class="math inline">\(d\approx2\)</span> cuando no existe autocorrelación de primer orden. La decisión formal se interpreta con las cotas <span class="math inline">\(d_L\)</span> y <span class="math inline">\(d_U\)</span> correspondientes al tamaño muestral y número de regresores; cuando esas cotas no están disponibles en el entorno de ejecución, se reporta el estadístico y su interpretación descriptiva sin inventar valores críticos.</p>
</section>
</section>
<section id="análisis-individual" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Análisis individual</h1>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fmt <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">d =</span> <span class="dv">4</span>) {</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(x) <span class="sc">==</span> <span class="dv">0</span> <span class="sc">||</span> <span class="fu">is.null</span>(x) <span class="sc">||</span> <span class="sc">!</span><span class="fu">is.finite</span>(x)) <span class="fu">return</span>(<span class="st">"NA"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatC</span>(x, <span class="at">format =</span> <span class="st">"f"</span>, <span class="at">digits =</span> d)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>fmt_p <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(x) <span class="sc">==</span> <span class="dv">0</span> <span class="sc">||</span> <span class="fu">is.null</span>(x) <span class="sc">||</span> <span class="sc">!</span><span class="fu">is.finite</span>(x)) <span class="fu">return</span>(<span class="st">"NA"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">format.pval</span>(x, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">eps =</span> <span class="fl">1e-4</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>decision_p <span class="ot">&lt;-</span> <span class="cf">function</span>(p, <span class="at">alpha =</span> <span class="fl">0.05</span>) {</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(p) <span class="sc">||</span> <span class="sc">!</span><span class="fu">is.finite</span>(p)) <span class="fu">return</span>(<span class="st">"no evaluable"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (p <span class="sc">&lt;</span> alpha) <span class="st">"se rechaza H0"</span> <span class="cf">else</span> <span class="st">"no se rechaza H0"</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>pref <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"01_Nile_media"</span>,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"02_nottem_mm"</span>,</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"03_LakeHuron_ses"</span>,</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"04_WWWusage_dmm"</span>,</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"05_airmiles_lineal"</span>,</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"06_UKDriverDeaths_cuadratica"</span>,</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"07_JohnsonJohnson_exponencial"</span>,</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"08_austres_holt"</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(resultados)) {</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> resultados[[i]]</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> x<span class="sc">$</span>resumen</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>  desc <span class="ot">&lt;-</span> x<span class="sc">$</span>descripcion</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>  lb <span class="ot">&lt;-</span> x<span class="sc">$</span>ljung_box_serie</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>  vr <span class="ot">&lt;-</span> x<span class="sc">$</span>validacion_residuos</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>  comp <span class="ot">&lt;-</span> x<span class="sc">$</span>comparacion</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n\n</span><span class="st">## "</span>, i, <span class="st">". "</span>, x<span class="sc">$</span>nombre, <span class="st">" — "</span>, r<span class="sc">$</span>metodo, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Descripción.** La serie tiene "</span>, desc<span class="sc">$</span>n, <span class="st">" observaciones, frecuencia "</span>,</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>    desc<span class="sc">$</span>frecuencia, <span class="st">", desde "</span>, desc<span class="sc">$</span>fecha_inicio, <span class="st">" hasta "</span>, desc<span class="sc">$</span>fecha_final,</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">". El tramo de estimación contiene "</span>, desc<span class="sc">$</span>observaciones_estimacion,</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">" observaciones y el tramo de validación contiene h = "</span>, desc<span class="sc">$</span>h_validacion,</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">" observaciones.</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"**Justificación del método.** "</span>, desc<span class="sc">$</span>justificacion, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"![Serie]("</span>, <span class="st">"../figs/"</span>, pref[i], <span class="st">"_serie.png"</span>, <span class="st">")</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"![Correlograma]("</span>, <span class="st">"../figs/"</span>, pref[i], <span class="st">"_correlograma.png"</span>, <span class="st">")</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"### Ljung--Box de la serie</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. "</span>,</span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Q = "</span>, <span class="fu">fmt</span>(lb<span class="sc">$</span>estadistico), <span class="st">", gl = "</span>, lb<span class="sc">$</span>gl,</span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">", valor crítico = "</span>, <span class="fu">fmt</span>(lb<span class="sc">$</span>valor_critico_5),</span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a>    <span class="st">" y p = "</span>, <span class="fu">fmt_p</span>(lb<span class="sc">$</span>p_valor), <span class="st">". "</span>,</span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">decision_p</span>(lb<span class="sc">$</span>p_valor), <span class="st">" al 5 %. "</span>,</span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(lb<span class="sc">$</span>p_valor <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb24-59"><a href="#cb24-59" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Existe evidencia de dependencia serial en la serie."</span>,</span>
<span id="cb24-60"><a href="#cb24-60" aria-hidden="true" tabindex="-1"></a>      <span class="st">"No se detecta evidencia suficiente de dependencia serial conjunta hasta el rezago evaluado."</span></span>
<span id="cb24-61"><a href="#cb24-61" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-62"><a href="#cb24-62" aria-hidden="true" tabindex="-1"></a>    <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-63"><a href="#cb24-63" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-64"><a href="#cb24-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-65"><a href="#cb24-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"### Autocorrelaciones individuales</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-66"><a href="#cb24-66" aria-hidden="true" tabindex="-1"></a>  sig <span class="ot">&lt;-</span> x<span class="sc">$</span>acf_serie[x<span class="sc">$</span>acf_serie<span class="sc">$</span>significativo, ]</span>
<span id="cb24-67"><a href="#cb24-67" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(sig) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb24-68"><a href="#cb24-68" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Ningún rezago evaluado supera la banda de ruido blanco.</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-69"><a href="#cb24-69" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb24-70"><a href="#cb24-70" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Los rezagos que superan la banda son: "</span>,</span>
<span id="cb24-71"><a href="#cb24-71" aria-hidden="true" tabindex="-1"></a>        <span class="fu">paste</span>(sig<span class="sc">$</span>lag, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">".</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-72"><a href="#cb24-72" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb24-73"><a href="#cb24-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-74"><a href="#cb24-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"### Ajuste, parámetros y optimización</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-75"><a href="#cb24-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Parámetros seleccionados: **"</span>, r<span class="sc">$</span>parametro, <span class="st">"**.</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-76"><a href="#cb24-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-77"><a href="#cb24-77" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(x<span class="sc">$</span>optimizacion)) {</span>
<span id="cb24-78"><a href="#cb24-78" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"La constante o ventana se obtuvo mediante la rejilla exigida, minimizando el MSE de un paso en el tramo de estimación.</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-79"><a href="#cb24-79" aria-hidden="true" tabindex="-1"></a>    opt_file <span class="ot">&lt;-</span> <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">2</span>) <span class="st">"02_nottem_mm_optimizacion.png"</span></span>
<span id="cb24-80"><a href="#cb24-80" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">3</span>) <span class="st">"03_LakeHuron_ses_optimizacion.png"</span></span>
<span id="cb24-81"><a href="#cb24-81" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">4</span>) <span class="st">"04_WWWusage_dmm_optimizacion.png"</span></span>
<span id="cb24-82"><a href="#cb24-82" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">8</span>) <span class="st">"08_austres_holt_optimizacion.png"</span></span>
<span id="cb24-83"><a href="#cb24-83" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="cn">NA_character_</span></span>
<span id="cb24-84"><a href="#cb24-84" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(opt_file)) <span class="fu">cat</span>(<span class="st">"![Optimización]("</span>, <span class="st">"../figs/"</span>, opt_file, <span class="st">")</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-85"><a href="#cb24-85" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb24-86"><a href="#cb24-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-87"><a href="#cb24-87" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (r<span class="sc">$</span>metodo <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"lineal"</span>, <span class="st">"cuadratica"</span>, <span class="st">"exponencial"</span>)) {</span>
<span id="cb24-88"><a href="#cb24-88" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"La tendencia se estimó mediante las ecuaciones normales. La tabla siguiente contiene los coeficientes y los errores estándar ordinarios y HAC de Bartlett.</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-89"><a href="#cb24-89" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(x<span class="sc">$</span>ajuste<span class="sc">$</span>parametros<span class="sc">$</span>coeficientes)</span>
<span id="cb24-90"><a href="#cb24-90" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-91"><a href="#cb24-91" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"R2 = "</span>, <span class="fu">fmt</span>(x<span class="sc">$</span>ajuste<span class="sc">$</span>parametros<span class="sc">$</span>R2),</span>
<span id="cb24-92"><a href="#cb24-92" aria-hidden="true" tabindex="-1"></a>        <span class="st">"; sigma² = "</span>, <span class="fu">fmt</span>(x<span class="sc">$</span>ajuste<span class="sc">$</span>parametros<span class="sc">$</span>sigma2),</span>
<span id="cb24-93"><a href="#cb24-93" aria-hidden="true" tabindex="-1"></a>        <span class="st">"; Durbin--Watson = "</span>, <span class="fu">fmt</span>(x<span class="sc">$</span>ajuste<span class="sc">$</span>parametros<span class="sc">$</span>DW), <span class="st">".</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-94"><a href="#cb24-94" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb24-95"><a href="#cb24-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-96"><a href="#cb24-96" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"### Medidas de error</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-97"><a href="#cb24-97" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-98"><a href="#cb24-98" aria-hidden="true" tabindex="-1"></a>    <span class="st">"| Tramo | MSE | MAD | MAPE | MASE |</span><span class="sc">\n</span><span class="st">|---|---:|---:|---:|---:|</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb24-99"><a href="#cb24-99" aria-hidden="true" tabindex="-1"></a>    <span class="st">"| Estimación | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MSE_estimacion), <span class="st">" | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MAD_estimacion),</span>
<span id="cb24-100"><a href="#cb24-100" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MAPE_estimacion), <span class="st">" | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MASE_estimacion), <span class="st">" |</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb24-101"><a href="#cb24-101" aria-hidden="true" tabindex="-1"></a>    <span class="st">"| Validación | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MSE_validacion), <span class="st">" | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MAD_validacion),</span>
<span id="cb24-102"><a href="#cb24-102" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MAPE_validacion), <span class="st">" | "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MASE_validacion), <span class="st">" |</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-103"><a href="#cb24-103" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-104"><a href="#cb24-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-105"><a href="#cb24-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"El referente utilizado fue **"</span>, comp<span class="sc">$</span>referencia,</span>
<span id="cb24-106"><a href="#cb24-106" aria-hidden="true" tabindex="-1"></a>      <span class="st">"**, cuyo MASE en validación fue "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MASE_ingenuo), <span class="st">".</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-107"><a href="#cb24-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-108"><a href="#cb24-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"### Validación de errores</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-109"><a href="#cb24-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-110"><a href="#cb24-110" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Se analizaron N = "</span>, vr<span class="sc">$</span>T, <span class="st">" errores de un paso y se usaron m = "</span>,</span>
<span id="cb24-111"><a href="#cb24-111" aria-hidden="true" tabindex="-1"></a>    vr<span class="sc">$</span>m, <span class="st">" rezagos, con p = "</span>, vr<span class="sc">$</span>p, <span class="st">" parámetros para corregir los grados de libertad.</span><span class="sc">\n\n</span><span class="st">"</span>,</span>
<span id="cb24-112"><a href="#cb24-112" aria-hidden="true" tabindex="-1"></a>    <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-113"><a href="#cb24-113" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-114"><a href="#cb24-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-115"><a href="#cb24-115" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"![ACF de residuos]("</span>, <span class="st">"../figs/"</span>, pref[i], <span class="st">"_acf_residuos.png"</span>, <span class="st">")</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-116"><a href="#cb24-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"![Errores]("</span>, <span class="st">"../figs/"</span>, pref[i], <span class="st">"_residuos_ajustados.png"</span>, <span class="st">")</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-117"><a href="#cb24-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-118"><a href="#cb24-118" aria-hidden="true" tabindex="-1"></a>  media <span class="ot">&lt;-</span> vr<span class="sc">$</span>media</span>
<span id="cb24-119"><a href="#cb24-119" aria-hidden="true" tabindex="-1"></a>  lb_e <span class="ot">&lt;-</span> vr<span class="sc">$</span>ljung_box</span>
<span id="cb24-120"><a href="#cb24-120" aria-hidden="true" tabindex="-1"></a>  jb <span class="ot">&lt;-</span> vr<span class="sc">$</span>jarque_bera</span>
<span id="cb24-121"><a href="#cb24-121" aria-hidden="true" tabindex="-1"></a>  dw <span class="ot">&lt;-</span> vr<span class="sc">$</span>durbin_watson</span>
<span id="cb24-122"><a href="#cb24-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-123"><a href="#cb24-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-124"><a href="#cb24-124" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Prueba t de media cero.** H0: μe = 0; H1: μe ≠ 0. "</span>,</span>
<span id="cb24-125"><a href="#cb24-125" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t = "</span>, <span class="fu">fmt</span>(media<span class="sc">$</span>estadistico), <span class="st">", gl = "</span>, media<span class="sc">$</span>gl,</span>
<span id="cb24-126"><a href="#cb24-126" aria-hidden="true" tabindex="-1"></a>    <span class="st">"; crítico = "</span>, <span class="fu">fmt</span>(media<span class="sc">$</span>valor_critico_5),</span>
<span id="cb24-127"><a href="#cb24-127" aria-hidden="true" tabindex="-1"></a>    <span class="st">"; p = "</span>, <span class="fu">fmt_p</span>(media<span class="sc">$</span>p_valor), <span class="st">"; "</span>,</span>
<span id="cb24-128"><a href="#cb24-128" aria-hidden="true" tabindex="-1"></a>    <span class="fu">decision_p</span>(media<span class="sc">$</span>p_valor), <span class="st">". "</span>,</span>
<span id="cb24-129"><a href="#cb24-129" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(media<span class="sc">$</span>p_valor <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb24-130"><a href="#cb24-130" aria-hidden="true" tabindex="-1"></a>      <span class="st">"La media de los errores difiere de cero de manera estadísticamente detectable."</span>,</span>
<span id="cb24-131"><a href="#cb24-131" aria-hidden="true" tabindex="-1"></a>      <span class="st">"No se detecta evidencia suficiente de que la media de los errores difiera de cero."</span></span>
<span id="cb24-132"><a href="#cb24-132" aria-hidden="true" tabindex="-1"></a>    ), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-133"><a href="#cb24-133" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-134"><a href="#cb24-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-135"><a href="#cb24-135" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-136"><a href="#cb24-136" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Ljung--Box de errores.** H0: r1 = ... = rm = 0; H1: alguna autocorrelación no es cero. "</span>,</span>
<span id="cb24-137"><a href="#cb24-137" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Q = "</span>, <span class="fu">fmt</span>(lb_e<span class="sc">$</span>estadistico), <span class="st">", gl = "</span>, lb_e<span class="sc">$</span>gl,</span>
<span id="cb24-138"><a href="#cb24-138" aria-hidden="true" tabindex="-1"></a>    <span class="st">", crítico = "</span>, <span class="fu">fmt</span>(lb_e<span class="sc">$</span>valor_critico_5),</span>
<span id="cb24-139"><a href="#cb24-139" aria-hidden="true" tabindex="-1"></a>    <span class="st">", p = "</span>, <span class="fu">fmt_p</span>(lb_e<span class="sc">$</span>p_valor), <span class="st">"; "</span>,</span>
<span id="cb24-140"><a href="#cb24-140" aria-hidden="true" tabindex="-1"></a>    <span class="fu">decision_p</span>(lb_e<span class="sc">$</span>p_valor), <span class="st">". "</span>,</span>
<span id="cb24-141"><a href="#cb24-141" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(lb_e<span class="sc">$</span>p_valor <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb24-142"><a href="#cb24-142" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Queda evidencia de autocorrelación remanente en los errores."</span>,</span>
<span id="cb24-143"><a href="#cb24-143" aria-hidden="true" tabindex="-1"></a>      <span class="st">"No se detecta evidencia suficiente de autocorrelación conjunta remanente."</span></span>
<span id="cb24-144"><a href="#cb24-144" aria-hidden="true" tabindex="-1"></a>    ), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-145"><a href="#cb24-145" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-146"><a href="#cb24-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-147"><a href="#cb24-147" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-148"><a href="#cb24-148" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Jarque--Bera.** H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. "</span>,</span>
<span id="cb24-149"><a href="#cb24-149" aria-hidden="true" tabindex="-1"></a>    <span class="st">"JB = "</span>, <span class="fu">fmt</span>(jb<span class="sc">$</span>estadistico), <span class="st">", gl = 2, crítico = "</span>, <span class="fu">fmt</span>(jb<span class="sc">$</span>valor_critico_5),</span>
<span id="cb24-150"><a href="#cb24-150" aria-hidden="true" tabindex="-1"></a>    <span class="st">", p = "</span>, <span class="fu">fmt_p</span>(jb<span class="sc">$</span>p_valor), <span class="st">"; "</span>, <span class="fu">decision_p</span>(jb<span class="sc">$</span>p_valor), <span class="st">". "</span>,</span>
<span id="cb24-151"><a href="#cb24-151" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(jb<span class="sc">$</span>p_valor <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb24-152"><a href="#cb24-152" aria-hidden="true" tabindex="-1"></a>      <span class="st">"La normalidad no queda respaldada por esta prueba."</span>,</span>
<span id="cb24-153"><a href="#cb24-153" aria-hidden="true" tabindex="-1"></a>      <span class="st">"No se detecta evidencia suficiente contra la normalidad mediante JB."</span></span>
<span id="cb24-154"><a href="#cb24-154" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-155"><a href="#cb24-155" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(vr<span class="sc">$</span>T <span class="sc">&lt;</span> <span class="dv">20</span>,</span>
<span id="cb24-156"><a href="#cb24-156" aria-hidden="true" tabindex="-1"></a>      <span class="st">" La interpretación es asintótica y debe tomarse con cautela porque N &lt; 20."</span>,</span>
<span id="cb24-157"><a href="#cb24-157" aria-hidden="true" tabindex="-1"></a>      <span class="st">""</span></span>
<span id="cb24-158"><a href="#cb24-158" aria-hidden="true" tabindex="-1"></a>    ), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-159"><a href="#cb24-159" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-160"><a href="#cb24-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-161"><a href="#cb24-161" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-162"><a href="#cb24-162" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Durbin--Watson.** H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. "</span>,</span>
<span id="cb24-163"><a href="#cb24-163" aria-hidden="true" tabindex="-1"></a>    <span class="st">"d = "</span>, <span class="fu">fmt</span>(dw),</span>
<span id="cb24-164"><a href="#cb24-164" aria-hidden="true" tabindex="-1"></a>    <span class="st">". La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. "</span>,</span>
<span id="cb24-165"><a href="#cb24-165" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</span><span class="sc">\n\n</span><span class="st">"</span>,</span>
<span id="cb24-166"><a href="#cb24-166" aria-hidden="true" tabindex="-1"></a>    <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-167"><a href="#cb24-167" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-168"><a href="#cb24-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-169"><a href="#cb24-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"### Comparación con el referente y cierre</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb24-170"><a href="#cb24-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-171"><a href="#cb24-171" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Conclusión.** El método "</span>, r<span class="sc">$</span>metodo, <span class="st">" con parámetros "</span>, r<span class="sc">$</span>parametro,</span>
<span id="cb24-172"><a href="#cb24-172" aria-hidden="true" tabindex="-1"></a>    <span class="st">" produjo MASE = "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MASE_validacion),</span>
<span id="cb24-173"><a href="#cb24-173" aria-hidden="true" tabindex="-1"></a>    <span class="st">" en validación, frente a MASE = "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>MASE_ingenuo),</span>
<span id="cb24-174"><a href="#cb24-174" aria-hidden="true" tabindex="-1"></a>    <span class="st">" del "</span>, comp<span class="sc">$</span>referencia, <span class="st">". La validación de residuos produjo p de Ljung--Box = "</span>,</span>
<span id="cb24-175"><a href="#cb24-175" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fmt_p</span>(r<span class="sc">$</span>LB_p), <span class="st">", p de Jarque--Bera = "</span>, <span class="fu">fmt_p</span>(r<span class="sc">$</span>JB_p),</span>
<span id="cb24-176"><a href="#cb24-176" aria-hidden="true" tabindex="-1"></a>    <span class="st">" y Durbin--Watson = "</span>, <span class="fu">fmt</span>(r<span class="sc">$</span>DW), <span class="st">".</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-177"><a href="#cb24-177" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-178"><a href="#cb24-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-179"><a href="#cb24-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(</span>
<span id="cb24-180"><a href="#cb24-180" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Recomendación.** El pronóstico se evalúa para el horizonte de "</span>, desc<span class="sc">$</span>h_validacion,</span>
<span id="cb24-181"><a href="#cb24-181" aria-hidden="true" tabindex="-1"></a>    <span class="st">" periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</span><span class="sc">\n\n</span><span class="st">"</span>,</span>
<span id="cb24-182"><a href="#cb24-182" aria-hidden="true" tabindex="-1"></a>    <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb24-183"><a href="#cb24-183" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-184"><a href="#cb24-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-185"><a href="#cb24-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"![Pronóstico final]("</span>, <span class="st">"../figs/"</span>, pref[i], <span class="st">"_final.png"</span>, <span class="st">")</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb24-186"><a href="#cb24-186" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<section id="nile-media" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="nile-media"><span class="header-section-number">5.1</span> 1. Nile — media</h2>
<p><strong>Descripción.</strong> La serie tiene 100 observaciones, frecuencia 1, desde -36159 hasta 0. El tramo de estimación contiene 88 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie anual sin estacionalidad explícita. La media histórica proporciona un pronóstico constante basado en toda la información disponible.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/01_Nile_media_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/01_Nile_media_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="ljungbox-de-la-serie"><span class="header-section-number">5.1.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 130.1800, gl = 24, valor crítico = 36.4150 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="autocorrelaciones-individuales"><span class="header-section-number">5.1.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13.</p>
</section>
<section id="ajuste-parámetros-y-optimización" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización"><span class="header-section-number">5.1.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>ninguno</strong>.</p>
</section>
<section id="medidas-de-error" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="medidas-de-error"><span class="header-section-number">5.1.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">31112.4881</td>
<td style="text-align: right;">145.0566</td>
<td style="text-align: right;">17.8874</td>
<td style="text-align: right;">1.0918</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">19867.9319</td>
<td style="text-align: right;">111.9943</td>
<td style="text-align: right;">13.5904</td>
<td style="text-align: right;">0.8429</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo</strong>, cuyo MASE en validación fue 0.8355.</p>
</section>
<section id="validación-de-errores" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="validación-de-errores"><span class="header-section-number">5.1.5</span> Validación de errores</h3>
<p>Se analizaron N = 87 errores de un paso y se usaron m = 21 rezagos, con p = 1 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/01_Nile_media_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/01_Nile_media_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = -5.7182, gl = 86; crítico = 1.9879; p = &lt; 1e-04; se rechaza H0. La media de los errores difiere de cero de manera estadísticamente detectable.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 22.8392, gl = 20, crítico = 31.4104, p = 0.2968; no se rechaza H0. No se detecta evidencia suficiente de autocorrelación conjunta remanente.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 0.2102, gl = 2, crítico = 5.9915, p = 0.9002; no se rechaza H0. No se detecta evidencia suficiente contra la normalidad mediante JB.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 0.9621. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre" class="level3" data-number="5.1.6">
<h3 data-number="5.1.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre"><span class="header-section-number">5.1.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método media con parámetros ninguno produjo MASE = 0.8429 en validación, frente a MASE = 0.8355 del ingenuo. La validación de residuos produjo p de Ljung–Box = 0.2968, p de Jarque–Bera = 0.9002 y Durbin–Watson = 0.9621.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/01_Nile_media_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="nottem-mm" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="nottem-mm"><span class="header-section-number">5.2</span> 2. nottem — mm</h2>
<p><strong>Descripción.</strong> La serie tiene 240 observaciones, frecuencia 12, desde -18263 hasta -10989. El tramo de estimación contiene 228 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie mensual. Se utiliza una media móvil para evaluar el comportamiento de corto plazo mediante un parámetro k seleccionado por MSE.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/02_nottem_mm_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/02_nottem_mm_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-1" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-1"><span class="header-section-number">5.2.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 2342.3833, gl = 24, valor crítico = 36.4150 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-1" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-1"><span class="header-section-number">5.2.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 23, 24.</p>
</section>
<section id="ajuste-parámetros-y-optimización-1" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-1"><span class="header-section-number">5.2.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>parametro=2</strong>.</p>
<p>La constante o ventana se obtuvo mediante la rejilla exigida, minimizando el MSE de un paso en el tramo de estimación.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/02_nottem_mm_optimizacion.png" class="img-fluid figure-img"></p>
<figcaption>Optimización</figcaption>
</figure>
</div>
</section>
<section id="medidas-de-error-1" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="medidas-de-error-1"><span class="header-section-number">5.2.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">47.0165</td>
<td style="text-align: right;">5.8040</td>
<td style="text-align: right;">12.0344</td>
<td style="text-align: right;">2.1120</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">102.6575</td>
<td style="text-align: right;">8.1417</td>
<td style="text-align: right;">15.1773</td>
<td style="text-align: right;">2.9626</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo estacional</strong>, cuyo MASE en validación fue 0.6186.</p>
</section>
<section id="validación-de-errores-1" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="validación-de-errores-1"><span class="header-section-number">5.2.5</span> Validación de errores</h3>
<p>Se analizaron N = 226 errores de un paso y se usaron m = 24 rezagos, con p = 1 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/02_nottem_mm_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/02_nottem_mm_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = 0.0194, gl = 225; crítico = 1.9706; p = 0.9846; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 1752.1155, gl = 23, crítico = 35.1725, p = &lt; 1e-04; se rechaza H0. Queda evidencia de autocorrelación remanente en los errores.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 8.8733, gl = 2, crítico = 5.9915, p = 0.01184; se rechaza H0. La normalidad no queda respaldada por esta prueba.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 0.5605. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-1" class="level3" data-number="5.2.6">
<h3 data-number="5.2.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-1"><span class="header-section-number">5.2.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método mm con parámetros parametro=2 produjo MASE = 2.9626 en validación, frente a MASE = 0.6186 del ingenuo estacional. La validación de residuos produjo p de Ljung–Box = &lt; 1e-04, p de Jarque–Bera = 0.01184 y Durbin–Watson = 0.5605.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/02_nottem_mm_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="lakehuron-ses" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="lakehuron-ses"><span class="header-section-number">5.3</span> 3. LakeHuron — ses</h2>
<p><strong>Descripción.</strong> La serie tiene 98 observaciones, frecuencia 1, desde -34698 hasta 730. El tramo de estimación contiene 86 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie anual. El suavizamiento exponencial simple permite actualizar el nivel con un peso alpha seleccionado mediante MSE.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/03_LakeHuron_ses_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/03_LakeHuron_ses_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-2" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-2"><span class="header-section-number">5.3.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 203.2368, gl = 24, valor crítico = 36.4150 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-2" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-2"><span class="header-section-number">5.3.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4, 5, 6, 7, 8, 9.</p>
</section>
<section id="ajuste-parámetros-y-optimización-2" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-2"><span class="header-section-number">5.3.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>parametro=0.98</strong>.</p>
<p>La constante o ventana se obtuvo mediante la rejilla exigida, minimizando el MSE de un paso en el tramo de estimación.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/03_LakeHuron_ses_optimizacion.png" class="img-fluid figure-img"></p>
<figcaption>Optimización</figcaption>
</figure>
</div>
</section>
<section id="medidas-de-error-2" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="medidas-de-error-2"><span class="header-section-number">5.3.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">0.5578</td>
<td style="text-align: right;">0.5767</td>
<td style="text-align: right;">0.0996</td>
<td style="text-align: right;">1.0045</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">2.1749</td>
<td style="text-align: right;">1.2294</td>
<td style="text-align: right;">0.2129</td>
<td style="text-align: right;">2.1413</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo</strong>, cuyo MASE en validación fue 2.1642.</p>
</section>
<section id="validación-de-errores-2" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="validación-de-errores-2"><span class="header-section-number">5.3.5</span> Validación de errores</h3>
<p>Se analizaron N = 85 errores de un paso y se usaron m = 21 rezagos, con p = 1 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/03_LakeHuron_ses_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/03_LakeHuron_ses_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = -0.1944, gl = 84; crítico = 1.9886; p = 0.8463; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 27.6166, gl = 20, crítico = 31.4104, p = 0.1188; no se rechaza H0. No se detecta evidencia suficiente de autocorrelación conjunta remanente.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 2.7195, gl = 2, crítico = 5.9915, p = 0.2567; no se rechaza H0. No se detecta evidencia suficiente contra la normalidad mediante JB.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 1.5456. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-2" class="level3" data-number="5.3.6">
<h3 data-number="5.3.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-2"><span class="header-section-number">5.3.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método ses con parámetros parametro=0.98 produjo MASE = 2.1413 en validación, frente a MASE = 2.1642 del ingenuo. La validación de residuos produjo p de Ljung–Box = 0.1188, p de Jarque–Bera = 0.2567 y Durbin–Watson = 1.5456.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/03_LakeHuron_ses_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="wwwusage-dmm" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="wwwusage-dmm"><span class="header-section-number">5.4</span> 4. WWWusage — dmm</h2>
<p><strong>Descripción.</strong> La serie tiene 100 observaciones, frecuencia 1, desde -719162 hasta -683003. El tramo de estimación contiene 88 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie con evolución temporal y tendencia local. La doble media móvil permite incorporar nivel y tendencia mediante k.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/04_WWWusage_dmm_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/04_WWWusage_dmm_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-3" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-3"><span class="header-section-number">5.4.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 647.7985, gl = 24, valor crítico = 36.4150 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-3" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-3"><span class="header-section-number">5.4.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24.</p>
</section>
<section id="ajuste-parámetros-y-optimización-3" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-3"><span class="header-section-number">5.4.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>parametro=2</strong>.</p>
<p>La constante o ventana se obtuvo mediante la rejilla exigida, minimizando el MSE de un paso en el tramo de estimación.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/04_WWWusage_dmm_optimizacion.png" class="img-fluid figure-img"></p>
<figcaption>Optimización</figcaption>
</figure>
</div>
</section>
<section id="medidas-de-error-3" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="medidas-de-error-3"><span class="header-section-number">5.4.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">22.6956</td>
<td style="text-align: right;">3.8294</td>
<td style="text-align: right;">3.0668</td>
<td style="text-align: right;">0.8609</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">50.9167</td>
<td style="text-align: right;">6.0833</td>
<td style="text-align: right;">2.8764</td>
<td style="text-align: right;">1.3676</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo</strong>, cuyo MASE en validación fue 7.6247.</p>
</section>
<section id="validación-de-errores-3" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="validación-de-errores-3"><span class="header-section-number">5.4.5</span> Validación de errores</h3>
<p>Se analizaron N = 85 errores de un paso y se usaron m = 21 rezagos, con p = 2 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/04_WWWusage_dmm_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/04_WWWusage_dmm_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = 0.2377, gl = 84; crítico = 1.9886; p = 0.8127; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 63.2611, gl = 19, crítico = 30.1435, p = &lt; 1e-04; se rechaza H0. Queda evidencia de autocorrelación remanente en los errores.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 1.2294, gl = 2, crítico = 5.9915, p = 0.5408; no se rechaza H0. No se detecta evidencia suficiente contra la normalidad mediante JB.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 1.1830. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-3" class="level3" data-number="5.4.6">
<h3 data-number="5.4.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-3"><span class="header-section-number">5.4.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método dmm con parámetros parametro=2 produjo MASE = 1.3676 en validación, frente a MASE = 7.6247 del ingenuo. La validación de residuos produjo p de Ljung–Box = &lt; 1e-04, p de Jarque–Bera = 0.5408 y Durbin–Watson = 1.1830.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/04_WWWusage_dmm_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="airmiles-lineal" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="airmiles-lineal"><span class="header-section-number">5.5</span> 5. airmiles — lineal</h2>
<p><strong>Descripción.</strong> La serie tiene 24 observaciones, frecuencia 1, desde -12053 hasta -3653. El tramo de estimación contiene 20 observaciones y el tramo de validación contiene h = 4 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie anual con crecimiento temporal. Se utiliza una tendencia lineal estimada mediante las ecuaciones normales.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/05_airmiles_lineal_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/05_airmiles_lineal_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-4" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-4"><span class="header-section-number">5.5.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 61.3067, gl = 6, valor crítico = 12.5916 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-4" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-4"><span class="header-section-number">5.5.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4.</p>
</section>
<section id="ajuste-parámetros-y-optimización-4" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-4"><span class="header-section-number">5.5.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>lineal</strong>.</p>
<p>La tendencia se estimó mediante las ecuaciones normales. La tabla siguiente contiene los coeficientes y los errores estándar ordinarios y HAC de Bartlett.</p>
<pre><code>            [,1]</code></pre>
<p>intercepto -4303.226 t 1086.983</p>
<p>R2 = 0.8807; sigma² = 5913940.4788; Durbin–Watson = 0.1960.</p>
</section>
<section id="medidas-de-error-4" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="medidas-de-error-4"><span class="header-section-number">5.5.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">5322546.4309</td>
<td style="text-align: right;">1970.9509</td>
<td style="text-align: right;">117.4294</td>
<td style="text-align: right;">1.6864</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">57251758.2894</td>
<td style="text-align: right;">7462.5985</td>
<td style="text-align: right;">26.8537</td>
<td style="text-align: right;">6.3852</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo</strong>, cuyo MASE en validación fue 4.4959.</p>
</section>
<section id="validación-de-errores-4" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="validación-de-errores-4"><span class="header-section-number">5.5.5</span> Validación de errores</h3>
<p>Se analizaron N = 20 errores de un paso y se usaron m = 5 rezagos, con p = 2 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/05_airmiles_lineal_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/05_airmiles_lineal_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = -0.0000, gl = 19; crítico = 2.0930; p = 1; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 18.6183, gl = 3, crítico = 7.8147, p = 0.0003279; se rechaza H0. Queda evidencia de autocorrelación remanente en los errores.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 1.4478, gl = 2, crítico = 5.9915, p = 0.4849; no se rechaza H0. No se detecta evidencia suficiente contra la normalidad mediante JB.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 0.1960. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-4" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-4"><span class="header-section-number">5.5.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método lineal con parámetros lineal produjo MASE = 6.3852 en validación, frente a MASE = 4.4959 del ingenuo. La validación de residuos produjo p de Ljung–Box = 0.0003279, p de Jarque–Bera = 0.4849 y Durbin–Watson = 0.1960.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 4 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/05_airmiles_lineal_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="ukdriverdeaths-cuadratica" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="ukdriverdeaths-cuadratica"><span class="header-section-number">5.6</span> 6. UKDriverDeaths — cuadratica</h2>
<p><strong>Descripción.</strong> La serie tiene 192 observaciones, frecuencia 12, desde -365 hasta 5448. El tramo de estimación contiene 180 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie mensual. Se utiliza una tendencia cuadrática para representar una posible curvatura en la evolución temporal.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/06_UKDriverDeaths_cuadratica_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/06_UKDriverDeaths_cuadratica_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-5" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-5"><span class="header-section-number">5.6.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 541.7120, gl = 24, valor crítico = 36.4150 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-5" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-5"><span class="header-section-number">5.6.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4, 9, 10, 11, 12, 13, 14, 22, 23, 24.</p>
</section>
<section id="ajuste-parámetros-y-optimización-5" class="level3" data-number="5.6.3">
<h3 data-number="5.6.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-5"><span class="header-section-number">5.6.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>cuadratica</strong>.</p>
<p>La tendencia se estimó mediante las ecuaciones normales. La tabla siguiente contiene los coeficientes y los errores estándar ordinarios y HAC de Bartlett.</p>
<pre><code>               [,1]</code></pre>
<p>intercepto 1778.6364405 t 1.3253233 t2 -0.0191131</p>
<p>R2 = 0.1812; sigma² = 66291.3739; Durbin–Watson = 0.7739.</p>
</section>
<section id="medidas-de-error-5" class="level3" data-number="5.6.4">
<h3 data-number="5.6.4" class="anchored" data-anchor-id="medidas-de-error-5"><span class="header-section-number">5.6.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">65186.5177</td>
<td style="text-align: right;">204.8156</td>
<td style="text-align: right;">12.1139</td>
<td style="text-align: right;">1.3097</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">50538.9299</td>
<td style="text-align: right;">187.2232</td>
<td style="text-align: right;">13.3252</td>
<td style="text-align: right;">1.1972</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo estacional</strong>, cuyo MASE en validación fue 0.7135.</p>
</section>
<section id="validación-de-errores-5" class="level3" data-number="5.6.5">
<h3 data-number="5.6.5" class="anchored" data-anchor-id="validación-de-errores-5"><span class="header-section-number">5.6.5</span> Validación de errores</h3>
<p>Se analizaron N = 180 errores de un paso y se usaron m = 24 rezagos, con p = 3 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/06_UKDriverDeaths_cuadratica_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/06_UKDriverDeaths_cuadratica_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = -0.0000, gl = 179; crítico = 1.9733; p = 1; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 412.9667, gl = 21, crítico = 32.6706, p = &lt; 1e-04; se rechaza H0. Queda evidencia de autocorrelación remanente en los errores.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 14.9154, gl = 2, crítico = 5.9915, p = 0.000577; se rechaza H0. La normalidad no queda respaldada por esta prueba.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 0.7739. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-5" class="level3" data-number="5.6.6">
<h3 data-number="5.6.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-5"><span class="header-section-number">5.6.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método cuadratica con parámetros cuadratica produjo MASE = 1.1972 en validación, frente a MASE = 0.7135 del ingenuo estacional. La validación de residuos produjo p de Ljung–Box = &lt; 1e-04, p de Jarque–Bera = 0.000577 y Durbin–Watson = 0.7739.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/06_UKDriverDeaths_cuadratica_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="johnsonjohnson-exponencial" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="johnsonjohnson-exponencial"><span class="header-section-number">5.7</span> 7. JohnsonJohnson — exponencial</h2>
<p><strong>Descripción.</strong> La serie tiene 84 observaciones, frecuencia 4, desde -3653 hasta 3926. El tramo de estimación contiene 72 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie trimestral con crecimiento aproximadamente multiplicativo. Se utiliza la transformación logarítmica para estimar una tendencia exponencial.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/07_JohnsonJohnson_exponencial_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/07_JohnsonJohnson_exponencial_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-6" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-6"><span class="header-section-number">5.7.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 685.3507, gl = 21, valor crítico = 32.6706 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-6" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-6"><span class="header-section-number">5.7.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21.</p>
</section>
<section id="ajuste-parámetros-y-optimización-6" class="level3" data-number="5.7.3">
<h3 data-number="5.7.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-6"><span class="header-section-number">5.7.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>exponencial</strong>.</p>
<p>La tendencia se estimó mediante las ecuaciones normales. La tabla siguiente contiene los coeficientes y los errores estándar ordinarios y HAC de Bartlett.</p>
<pre><code>beta0     beta1 </code></pre>
<p>0.4981558 1.0436966</p>
<p>R2 = 0.9727; sigma² = 0.0228; Durbin–Watson = 1.6898.</p>
</section>
<section id="medidas-de-error-6" class="level3" data-number="5.7.4">
<h3 data-number="5.7.4" class="anchored" data-anchor-id="medidas-de-error-6"><span class="header-section-number">5.7.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">0.3222</td>
<td style="text-align: right;">0.3637</td>
<td style="text-align: right;">11.8986</td>
<td style="text-align: right;">0.6927</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">7.7384</td>
<td style="text-align: right;">1.8450</td>
<td style="text-align: right;">16.5379</td>
<td style="text-align: right;">3.5142</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo estacional</strong>, cuyo MASE en validación fue 6.5286.</p>
</section>
<section id="validación-de-errores-6" class="level3" data-number="5.7.5">
<h3 data-number="5.7.5" class="anchored" data-anchor-id="validación-de-errores-6"><span class="header-section-number">5.7.5</span> Validación de errores</h3>
<p>Se analizaron N = 72 errores de un paso y se usaron m = 18 rezagos, con p = 2 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/07_JohnsonJohnson_exponencial_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/07_JohnsonJohnson_exponencial_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = 0.2090, gl = 71; crítico = 1.9939; p = 0.8351; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 108.5986, gl = 16, crítico = 26.2962, p = &lt; 1e-04; se rechaza H0. Queda evidencia de autocorrelación remanente en los errores.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 111.5297, gl = 2, crítico = 5.9915, p = &lt; 1e-04; se rechaza H0. La normalidad no queda respaldada por esta prueba.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 1.2914. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-6" class="level3" data-number="5.7.6">
<h3 data-number="5.7.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-6"><span class="header-section-number">5.7.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método exponencial con parámetros exponencial produjo MASE = 3.5142 en validación, frente a MASE = 6.5286 del ingenuo estacional. La validación de residuos produjo p de Ljung–Box = &lt; 1e-04, p de Jarque–Bera = &lt; 1e-04 y Durbin–Watson = 1.2914.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/07_JohnsonJohnson_exponencial_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
<section id="austres-holt" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="austres-holt"><span class="header-section-number">5.8</span> 8. austres — holt</h2>
<p><strong>Descripción.</strong> La serie tiene 89 observaciones, frecuencia 4, desde 455 hasta 8491. El tramo de estimación contiene 77 observaciones y el tramo de validación contiene h = 12 observaciones.</p>
<p><strong>Justificación del método.</strong> Serie trimestral con nivel y tendencia. Holt actualiza ambos componentes mediante alpha y beta seleccionados por MSE.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/08_austres_holt_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/08_austres_holt_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma</figcaption>
</figure>
</div>
<section id="ljungbox-de-la-serie-7" class="level3" data-number="5.8.1">
<h3 data-number="5.8.1" class="anchored" data-anchor-id="ljungbox-de-la-serie-7"><span class="header-section-number">5.8.1</span> Ljung–Box de la serie</h3>
<p>H0: todas las autocorrelaciones hasta m son cero; H1: al menos una es distinta de cero. Q = 938.9522, gl = 22, valor crítico = 33.9244 y p = &lt; 1e-04. se rechaza H0 al 5 %. Existe evidencia de dependencia serial en la serie.</p>
</section>
<section id="autocorrelaciones-individuales-7" class="level3" data-number="5.8.2">
<h3 data-number="5.8.2" class="anchored" data-anchor-id="autocorrelaciones-individuales-7"><span class="header-section-number">5.8.2</span> Autocorrelaciones individuales</h3>
<p>Los rezagos que superan la banda son: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22.</p>
</section>
<section id="ajuste-parámetros-y-optimización-7" class="level3" data-number="5.8.3">
<h3 data-number="5.8.3" class="anchored" data-anchor-id="ajuste-parámetros-y-optimización-7"><span class="header-section-number">5.8.3</span> Ajuste, parámetros y optimización</h3>
<p>Parámetros seleccionados: <strong>alpha=0.95, beta=0.8</strong>.</p>
<p>La constante o ventana se obtuvo mediante la rejilla exigida, minimizando el MSE de un paso en el tramo de estimación.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/08_austres_holt_optimizacion.png" class="img-fluid figure-img"></p>
<figcaption>Optimización</figcaption>
</figure>
</div>
</section>
<section id="medidas-de-error-7" class="level3" data-number="5.8.4">
<h3 data-number="5.8.4" class="anchored" data-anchor-id="medidas-de-error-7"><span class="header-section-number">5.8.4</span> Medidas de error</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tramo</th>
<th style="text-align: right;">MSE</th>
<th style="text-align: right;">MAD</th>
<th style="text-align: right;">MAPE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimación</td>
<td style="text-align: right;">129.3284</td>
<td style="text-align: right;">7.5298</td>
<td style="text-align: right;">0.0514</td>
<td style="text-align: right;">0.0359</td>
</tr>
<tr class="even">
<td>Validación</td>
<td style="text-align: right;">8207.2350</td>
<td style="text-align: right;">78.4718</td>
<td style="text-align: right;">0.4486</td>
<td style="text-align: right;">0.3742</td>
</tr>
</tbody>
</table>
<p>El referente utilizado fue <strong>ingenuo estacional</strong>, cuyo MASE en validación fue 1.9903.</p>
</section>
<section id="validación-de-errores-7" class="level3" data-number="5.8.5">
<h3 data-number="5.8.5" class="anchored" data-anchor-id="validación-de-errores-7"><span class="header-section-number">5.8.5</span> Validación de errores</h3>
<p>Se analizaron N = 76 errores de un paso y se usaron m = 19 rezagos, con p = 2 parámetros para corregir los grados de libertad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/08_austres_holt_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/08_austres_holt_residuos_ajustados.png" class="img-fluid figure-img"></p>
<figcaption>Errores</figcaption>
</figure>
</div>
<p><strong>Prueba t de media cero.</strong> H0: μe = 0; H1: μe ≠ 0. t = 0.8151, gl = 75; crítico = 1.9921; p = 0.4176; no se rechaza H0. No se detecta evidencia suficiente de que la media de los errores difiera de cero.</p>
<p><strong>Ljung–Box de errores.</strong> H0: r1 = … = rm = 0; H1: alguna autocorrelación no es cero. Q = 41.5037, gl = 17, crítico = 27.5871, p = 0.0007906; se rechaza H0. Queda evidencia de autocorrelación remanente en los errores.</p>
<p><strong>Jarque–Bera.</strong> H0: asimetría = 0 y curtosis = 3; H1: al menos una condición falla. JB = 385.9364, gl = 2, crítico = 5.9915, p = &lt; 1e-04; se rechaza H0. La normalidad no queda respaldada por esta prueba.</p>
<p><strong>Durbin–Watson.</strong> H0: ausencia de autocorrelación de primer orden; H1: presencia de autocorrelación de primer orden. d = 1.4720. La decisión formal requiere las cotas dL y dU de las tablas correspondientes; no se inventan valores críticos. Descriptivamente, un valor cercano a 2 es compatible con poca autocorrelación de primer orden.</p>
</section>
<section id="comparación-con-el-referente-y-cierre-7" class="level3" data-number="5.8.6">
<h3 data-number="5.8.6" class="anchored" data-anchor-id="comparación-con-el-referente-y-cierre-7"><span class="header-section-number">5.8.6</span> Comparación con el referente y cierre</h3>
<p><strong>Conclusión.</strong> El método holt con parámetros alpha=0.95, beta=0.8 produjo MASE = 0.3742 en validación, frente a MASE = 1.9903 del ingenuo estacional. La validación de residuos produjo p de Ljung–Box = 0.0007906, p de Jarque–Bera = &lt; 1e-04 y Durbin–Watson = 1.4720.</p>
<p><strong>Recomendación.</strong> El pronóstico se evalúa para el horizonte de 12 periodos usado en la validación. El límite principal se evidencia mediante el MASE frente al referente y la posible autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/08_austres_holt_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico final</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="contraejemplo" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Contraejemplo</h1>
<p>El contraejemplo deliberado utiliza <code>AirPassengers</code> con la media histórica. La justificación del ejercicio es que la serie presenta una estructura estacional fuerte y crecimiento, mientras que la media histórica no representa explícitamente esos componentes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>contraejemplo<span class="sc">$</span>descripcion</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$serie
[1] "AirPassengers"

$fuente
[1] "R: datasets::AirPassengers (help('AirPassengers'))"

$unidad
[1] "miles de pasajeros"

$n
[1] 144

$frecuencia
[1] 12

$fecha_inicio
[1] "1949-01-01"

$fecha_final
[1] "1960-12-01"

$h_validacion
[1] 12

$observaciones_estimacion
[1] 132

$justificacion
[1] "Contraejemplo deliberado. La serie presenta estructura estacional y crecimiento, mientras que la media histórica no representa explícitamente esos componentes."</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>contraejemplo<span class="sc">$</span>resumen</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 17
  serie         metodo parametro MSE_estimacion MAD_estimacion MAPE_estimacion MASE_estimacion
  &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;              &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
1 AirPassengers media  ninguno           11494.           83.4            26.8            2.74
# ℹ 10 more variables: MSE_validacion &lt;dbl&gt;, MAD_validacion &lt;dbl&gt;, MAPE_validacion &lt;dbl&gt;,
#   MASE_validacion &lt;dbl&gt;, MASE_ingenuo &lt;dbl&gt;, optimo_en_borde &lt;lgl&gt;, LB_p &lt;dbl&gt;, JB_p &lt;dbl&gt;,
#   DW &lt;dbl&gt;, LB_serie_p &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>contraejemplo<span class="sc">$</span>acf_serie</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 5
     lag   acf limite_inferior limite_superior significativo
   &lt;int&gt; &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt; &lt;lgl&gt;        
 1     1 0.948          -0.163           0.163 TRUE         
 2     2 0.876          -0.163           0.163 TRUE         
 3     3 0.807          -0.163           0.163 TRUE         
 4     4 0.753          -0.163           0.163 TRUE         
 5     5 0.714          -0.163           0.163 TRUE         
 6     6 0.682          -0.163           0.163 TRUE         
 7     7 0.663          -0.163           0.163 TRUE         
 8     8 0.656          -0.163           0.163 TRUE         
 9     9 0.671          -0.163           0.163 TRUE         
10    10 0.703          -0.163           0.163 TRUE         
# ℹ 14 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>contraejemplo<span class="sc">$</span>validacion_residuos<span class="sc">$</span>ljung_box</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$estadistico
[1] 869.6156

$gl
[1] 23

$valor_critico_5
[1] 35.17246

$p_valor
[1] 6.346739e-169

$rechazar_5
[1] TRUE</code></pre>
</div>
</div>
<p>La evidencia de fallo se interpreta conjuntamente mediante el patrón de la serie, el MASE de validación y la autocorrelación remanente de los errores.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/09_AirPassengers_contraejemplo_serie.png" class="img-fluid figure-img"></p>
<figcaption>Serie AirPassengers</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/09_AirPassengers_contraejemplo_correlograma.png" class="img-fluid figure-img"></p>
<figcaption>Correlograma AirPassengers</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/09_AirPassengers_contraejemplo_acf_residuos.png" class="img-fluid figure-img"></p>
<figcaption>ACF de residuos del contraejemplo</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/09_AirPassengers_contraejemplo_final.png" class="img-fluid figure-img"></p>
<figcaption>Pronóstico del contraejemplo</figcaption>
</figure>
</div>
</section>
<section id="verificaciones-de-implementación" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Verificaciones de implementación</h1>
<p>La ejecución incluye la verificación de la ACF manual frente a <code>acf(plot = FALSE)</code>. La diferencia máxima debe ser menor que <span class="math inline">\(10^{-12}\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Diferencia máxima ACF:"</span>, diferencia_acf, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Diferencia máxima ACF: 4.440892e-16 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Coincide:"</span>, diferencia_acf <span class="sc">&lt;</span> <span class="fl">1e-12</span>, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coincide: TRUE </code></pre>
</div>
</div>
</section>
<section id="conclusiones-generales" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusiones generales</h1>
<p>Los ocho ejemplos cubren, en el orden exigido, media histórica, media móvil, suavizamiento exponencial simple, doble media móvil, tendencia lineal, tendencia cuadrática, tendencia exponencial y Holt lineal. La comparación de MASE en el tramo de validación permite valorar cada ajuste frente a su referente ingenuo correspondiente.</p>
<p>La elección de las constantes o ventanas se realiza mediante la rejilla definida en la tarea. Las pruebas sobre los errores permiten revisar la media cero, la autocorrelación, la normalidad y la autocorrelación de primer orden.</p>
</section>
<section id="reproducibilidad" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Reproducibilidad</h1>
<p>Desde la raíz del repositorio:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"ejemplos/ejemplos.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>El informe utiliza las mismas funciones, datos, parámetros y figuras generadas por <code>ejemplos.R</code>.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>